name: Upload to PyPI

on:
  release:
    types: [published]

jobs:
  pypi:
    uses: MAK-Relic-Tool/Workflows/.github/workflows/publish-to-pypi.yml@main
    with:
      pypi-token: ${{ secrets.PYPI_API_TOKEN }}
