name: Pytest

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/pytest.yml'
      - 'setup.cfg'
      - 'setup.py'
      - 'MANIFEST.in'
      - 'test-requirements.txt'

  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/pytest.yml'
      - 'setup.cfg'
      - 'setup.py'
      - 'MANIFEST.in'
      - 'test-requirements.txt'

jobs:
  pytest:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    name: Pytest ${{ matrix.python-version }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade Pip
      run: |
        python -m pip install --upgrade pip

    - name: Install Tools (Wheel, Setuptools, Pytest)
      run: |
        python -m pip install wheel setuptools pytest

    - name: Install Testing Requirements
      run: |
        if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi

    - name: Build & Install Repo
      run: |
        python -m pip install .

    - name: Run Pytest
      run: |
        pytest -v